name: flutter_browser_scroll
description: Browser-driven outer page scrolling for Flutter Web.
version: 0.1.0
homepage: https://github.com/flutter-zl/flutter-browser-scroll
repository: https://github.com/flutter-zl/flutter-browser-scroll
issue_tracker: https://github.com/flutter-zl/flutter-browser-scroll/issues
topics:
  - flutter-web
  - scrolling
  - browser

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
